name: Build Obfuscate BPB Panel

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 1 * * *"  # Runs everyday at 1:00 AM

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install javascript-obfuscator
        run: npm install -g javascript-obfuscator

      - name: Download BPB worker script
        run: wget -O origin.js https://raw.githubusercontent.com/bia-pain-bache/BPB-Worker-Panel/main/build/unobfuscated-worker.js

      - name: Obfuscate script
        run: |
          javascript-obfuscator origin.js --output _worker.js \
          --compact true \
          --control-flow-flattening \
          --dead-code-injection \
          --identifier-names-generator hexadecimal \
          --rename-globals \
          --string-array \
          --string-array-encoding rc4 \
          --transform-object-keys \
          --unicode-escape-sequence

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: ':arrow_up: update latest bpb panel'
